### ISSUE TITLE
Save tensors as tensor and not as vector

### ISSUE THREAD

**Issue by Nobody-86** [calculix/ccx2paraview#27]
Hi,
I've been using this converter for a few days now and I really like it. However, I noticed that stress components seem to be stored as vectors. This means that tensor operations in the python calculator such as eigenvector(S) are not possible. Would it possibly make sense to store tensor quantities as tensors? Or is there a specific reason that it is exported as a vector?

Currently I convert the vectors to tensors in a ProgrammableFilter:

def make_tensor(xx,yy,zz,xy,yz,xz):
    t = np.array([])
    for i in range(len(xx)):
        t_i = np.array([[xx[i],xy[i],xz[i]],[xy[i],yy[i],yz[i]],[xz[i],yz[i],zz[i]]])
        t = np.append(t, t_i)
    t = dsa.VTKArray(t)
    t.shape=(len(xx),3,3)
    return t

sxx = inputs[0].PointData["S"][:,0]
syy = inputs[0].PointData["S"][:,1]
szz = inputs[0].PointData["S"][:,2]
sxy = inputs[0].PointData["S"][:,3]
syz = inputs[0].PointData["S"][:,4]
sxz = inputs[0].PointData["S"][:,5]

stress = make_tensor(sxx,syy,szz,sxy,syz,sxz)

But this is very slow.

**Comment by imirzov** [comment]
Hi and I'm sorry for such a late answer. After researching this topic during a several evenings it looks like that I can not propose something useful for you.

So, first, stress components are not stored as vectors. All point data is stored as vtkDoubleArray. None of data arrays are marked as Vectors, Scalars or Tensors since this feature supports only one data array. It means that point data can contain maximum one Scalar data array, maximum one Vector data array etc. Pardon, I will not mark stress as Tensor but leave strain as is.

Second, if I correctly understood, you mean that tensor is an array with 3x3 dimensions. Storing 9 components instead of 6 will increase file size. In FRD file tensor data has 6 components, and so do I.

The script you provided is not complete and it also does not mark resulting data array as a tensor. It only converts 6 valued data array to 9 values at each node.

Also I've tried operation 'eigenvector(stress)' in Python Calculator after applying your script. Operation does not produce vector field, so I do not understand why it is useful.

From my point of view the code works fine and converts FRD to VTK correctly. If you need some additional functionality in Paraview, please, code your own Python filters for Paraview. But it is not relevant to data conversion and should not be solved by this converter.

**Comment by imirzov** [comment]
I slightly optimized your code:
```python
import numpy as np 
res = np.array([])
pd = inputs[0].PointData['S']
for xx,yy,zz,xy,yz,xz in pd:
    t = np.array([[xx,xy,xz],[xy,yy,yz],[xz,yz,zz]])
    res = np.append(res, t)
tensor = dsa.VTKArray(res)
tensor.shape = (len(pd), 3, 3)
output.PointData.append(tensor, 'S_tensor')
```
